# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: willibrandon.dotsider
PackageVersion: 0.26.1
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: msi
Scope: machine
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/willibrandon/dotsider/releases/download/v0.26.1/dotsider-win-x64.msi
    InstallerSha256: 7120066F5B10B00A82E148DA91FB7BA3EF7E66B0A356CF21A00CBF90BE8A7111
    ProductCode: "{598906A6-CC24-4480-A72A-11A4081E4C44}"
  - Architecture: arm64
    InstallerUrl: https://github.com/willibrandon/dotsider/releases/download/v0.26.1/dotsider-win-arm64.msi
    InstallerSha256: 2F2AAAB59C196D7419CA29D5557339334C777071A8FAAEFE83CADDCDA04FE29A
    ProductCode: "{4D2699A5-6DB1-4BD8-ABEE-C88DEFAF211B}"
ManifestType: installer
ManifestVersion: 1.9.0
